name: Deploy UATS microservices
on:
  push:
    branches:
      - main # Add more branches
jobs:
  prepare:
    name: Prepare Workspace
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Get Branch Details
        uses: rlespinasse/github-slug-action@v3.x
      - name: Set environment details
        id: prepare-env
        run: |
          echo "::set-output name=environment_name::${GITHUB_REF_SLUG}";
          echo "::set-output name=eks_host_key::EKS_HOST_${GITHUB_REF_SLUG}";
          echo "::set-output name=eks_certificate_key::EKS_CERT_${GITHUB_REF_SLUG}";
          echo "::set-output name=eks_region_key::EKS_REGION_${GITHUB_REF_SLUG}";
    outputs:
      environment_name: ${{ steps.prepare-env.outputs.environment_name }}
      eks_host_key: ${{ steps.prepare-env.outputs.eks_host_key }}
      eks_certificate_key: ${{ steps.prepare-env.outputs.eks_certificate_key }}
      eks_region_key: ${{ steps.prepare-env.outputs.eks_region_key }}
  deploy:
    name: Deploy microservices
    needs:
      - prepare
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      ENV_NAME: ${{ needs.prepare.outputs.environment_name }}
      EKS_HOST_KEY: ${{ needs.prepare.outputs.eks_host_key }}
      EKS_CERTIFICATE_KEY: ${{ needs.prepare.outputs.eks_certificate_key }}
      EKS_REGION_KEY: ${{ needs.prepare.outputs.eks_region_key }}
      TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
      TF_BACKEND_REGION: ${{ secrets.TF_BACKEND_REGION }}
      TF_BACKEND_KEY: terraform/$ENV_NAME-kubernetes-cluster.tfstate
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.TF_BACKEND_REGION }}
      - name: Run Terraform configurations
        env:
          EKS_HOST: ${{ secrets[env.EKS_HOST_KEY] }}
          EKS_CERTIFICATE: ${{ secrets[env.EKS_CERTIFICATE_KEY] }}
          EKS_REGION: ${{ secrets[env.EKS_REGION_KEY] }}
          POD_AWS_ACCESS_KEY_ID: ${{ secrets.POD_ACCESS_KEY_ID }}
          POD_AWS_SECRET_ACCESS_KEY: ${{ secrets.POD_SECRET_ACCESS_KEY }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_GEN2 }}
        run: |
          cd ./terraform
          terraform init \
            -backend-config="bucket=$TF_BACKEND_BUCKET" \
            -backend-config="region=$TF_BACKEND_REGION" \
            -backend-config="key=$TF_BACKEND_KEY" \
            --reconfigure
          terraform apply \
            -var "eks_host=$EKS_HOST" \
            -var "eks_certificate=$EKS_CERTIFICATE" \
            -var "environment=$ENV_NAME" \
            -var "AWS_REGION=$EKS_REGION" \
            -var "POD_AWS_ACCESS_KEY_ID=$POD_AWS_ACCESS_KEY_ID" \
            -var "POD_AWS_SECRET_ACCESS_KEY=$POD_AWS_SECRET_ACCESS_KEY" \
            -var "ECR_REGISTRY=$ECR_REGISTRY" \
            -var "ECR_REPOSITORY=$ECR_REPOSITORY" \
            --auto-approve
          echo "$ENV_NAME is deployed"

